{
 "title": "Mikrotik snmp prometheus",
 "description": "Mikrotik snmp monitoring (prometheus)",
 "tags": [
  "prometheus",
  "Mikrotik",
  "Hap ac",
  "snmp",
  "snmp v3"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "Job",
    "query": {
     "query": "label_values(ifHCInOctets,  job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(ifHCInOctets,  instance)"
    }
   },
   {
    "name": "index",
    "query": {
     "query": "label_values(ifHighSpeed{instance='$instance'},ifIndex)"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "query_result(sort(ifIndex{ifName=~'^(ether).+',instance='$instance'}) or sort(ifIndex{ifName=~'^(sfp|wlan).+',instance='$instance'}) or sort(ifIndex{ifName=~'^bridge.+',instance='$instance'}) or  sort(ifIndex{ifName!~'^(ether|bridge).+',instance='$instance'}) )"
    }
   },
   {
    "name": "desc",
    "query": {
     "query": "query_result(ifHCInOctets{ifName=\"$Interface\",instance=\"$instance\"})"
    }
   },
   {
    "name": "queuesimple_name",
    "query": {
     "query": "query_result((mtxrQueueSimplePacketsIn * on (mtxrQueueSimpleIndex) group_left(mtxrQueueSimpleName) mtxrQueueSimpleName{instance='$instance',}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance='$instance'}/100"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mtxrHlTemperature/10" }
   ]
  },
  {
   "title": "Load CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrProcessorLoad{instance='$instance'}"
    }
   ]
  },
  {
   "title": "Firmware version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mtxrFirmwareVersion{instance='$instance'}",
     "legendFormat": "{{mtxrFirmwareVersion}}"
    }
   ]
  },
  {
   "title": "CPU Mhz",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrHlProcessorFrequency{instance='$instance'}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "mtxrHlVoltage/10", "legendFormat": "Voltage" }
   ]
  },
  {
   "title": "System identity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysIdentity{instance='$instance'}",
     "legendFormat": "{{sysIdentity}}"
    }
   ]
  },
  {
   "title": "Active Fan",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mtxrHlActiveFan{instance='$instance'}",
     "legendFormat": "{{mtxrHlActiveFan}}"
    }
   ]
  },
  {
   "title": "License level",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrLicLevel{instance='$instance'}",
     "legendFormat": "Lic"
    },
    { "expr": "mtxrLicUpgradableTo", "legendFormat": "Lic Upgradable To" }
   ]
  },
  {
   "title": "Board Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrBoardName{instance='$instance'}",
     "legendFormat": "{{mtxrBoardName}}"
    }
   ]
  },
  {
   "title": "Load RAM",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(hrStorageUsed{hrStorageIndex='65536',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='65536',instance='$instance'})"
    }
   ]
  },
  {
   "title": "Load system disk",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(hrStorageUsed{hrStorageIndex='131072',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='131072',instance='$instance'})"
    }
   ]
  },
  {
   "title": "System",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "hrProcessorLoad{instance='$instance'}",
     "legendFormat": "Load CPU"
    },
    { "expr": "mtxrHlTemperature/10", "legendFormat": "CPU Temp °C" },
    {
     "expr": "(hrStorageUsed{hrStorageIndex='65536',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='65536',instance='$instance'})",
     "legendFormat": "RAM usage"
    },
    {
     "expr": "(hrStorageUsed{hrStorageIndex='131072',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='131072',instance='$instance'})",
     "legendFormat": "System disk"
    }
   ]
  },
  {
   "title": "MTU",
   "type": "graph",
   "description": "Maximum Transmission Unit",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "MTU", "label": "Maximum Transmission Unit" }
   ],
   "targets": [
    { "expr": "ifMtu{instance='$instance'}", "legendFormat": "{{ifName}}" }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sysDescr{instance='$instance'}", "legendFormat": "{{sysDescr}}" }
   ]
  },
  {
   "title": "DHCP Leases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mtxrDHCPLeaseCount", "legendFormat": "dhcp leases" }
   ]
  },
  {
   "title": "Interfaces",
   "type": "table",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ifPhysAddress{instance='$instance'}"
    },
    {
     "expr": "ifOperStatus{instance='$instance'}"
    },
    {
     "expr": "mtxrInterfaceStatsRxBytes{instance='$instance'}"
    },
    {
     "expr": "mtxrInterfaceStatsTxBytes{instance='$instance'}"
    },
    { "expr": "ifSpeed{instance='$instance'}" }
   ]
  },
  {
   "title": "Wi-Fi Client count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mtxrWlApAuthClientCount", "legendFormat": "{{mtxrWlApIndex}}" }
   ]
  },
  {
   "title": "Wi-Fi CCQ & Noise",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mtxrWlApOverallTxCCQ{instance='$instance'}",
     "legendFormat": "CCQ - {{mtxrWlApIndex}}"
    },
    {
     "expr": "mtxrWlApNoiseFloor{instance='$instance'}",
     "legendFormat": "Noise - {{mtxrWlApIndex}}"
    }
   ]
  },
  {
   "title": "Multicast Pkts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "pps", "label": "packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{job='Mikrotik',ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "In - {{ifName}}"
    },
    {
     "expr": "irate(ifHCOutMulticastPkts{job='Mikrotik',ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Out - {{ifName}}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
     "legendFormat": "In - {{ifName}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
     "legendFormat": "Out - {{ifName}}"
    }
   ]
  },
  {
   "title": "Queue all",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(irate(mtxrQueueSimpleBytesIn[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{instance='$instance'})*8 ",
     "legendFormat": "In - {{mtxrQueueSimpleName}}"
    },
    {
     "expr": "(irate(mtxrQueueSimpleBytesOut[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{instance='$instance'})*8",
     "legendFormat": "Out - {{mtxrQueueSimpleName}}"
    }
   ]
  },
  {
   "title": "POE Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrPOEStatus{instance='$instance'}"
    }
   ]
  },
  {
   "title": "POE Current",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(mtxrPOECurrent{instance='$instance'}[$__rate_interval])",
     "legendFormat": "POE Current"
    }
   ]
  },
  {
   "title": "POE Voltage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrPOEVoltage{instance='$instance'}",
     "legendFormat": "POE Voltage"
    }
   ]
  },
  {
   "title": "POE Power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrPOEPower{instance='$instance'}",
     "legendFormat": "POE Power"
    }
   ]
  }
 ]
}